### PR TITLE
UTF-8 issues in strings

### PR DESCRIPTION
**Pull request by ovilanova**
Fix possible issues with accents and non-ASCII symbols

### CODE REVIEW

**Comment by lifelike** [comment]
Not 100% sure about this. Perhaps it is better to fix this earlier when parsing the CSV-file so that the strings are all unicode internally instead (which would also solve issues with someone using UTF-8 in filenames for images for instance)? Some more testing (and new tests) would be required to know that nothing else currently relies on things being just ascii.

Either way it has to be documented somewhere (when things are documented...) that only UTF-8 encoded CSV-files are supported, because obviously things will break if someone tries to use a file in some other encoding.

**Comment by mfaella** [comment]
I also run into this issue and fixed it with the following, slightly more conservative, approach:
```
try:
    c.text = text
except ValueError as err:
    c.text = unicode(text, "utf_8")
```

**Comment by theclue** [comment]
same issue, but neither these two proposed solutions is working for my italian cards (I have a "più" in a description). I got this exception: 

Traceback (most recent call last):
  File "countersheet.py", line 1272, in <module>
    effect.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 268, in affect
    self.effect()
  File "countersheet.py", line 810, in effect
    positions[box].y+rowy)
  File "countersheet.py", line 419, in generatecounter
    string_replace_xml_text(clone, "%%%s%%" % name, value)
  File "countersheet.py", line 1259, in string_replace_xml_text
    string_replace_xml_text(c, pattern, value)
  File "countersheet.py", line 1259, in string_replace_xml_text
    string_replace_xml_text(c, pattern, value)
  File "countersheet.py", line 1257, in string_replace_xml_text
    element.text = element.text.replace(pattern, value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)

**Comment by lifelike** [comment]
I can also reproduce the same problem theclue reported.  Some more stable fix is required. Perhaps make this an issue or make an improved fix to merge?

**Comment by lifelike** [comment]
Added a decode also when substituting parts of strings. This seems to work. Thanks everyone!

It will break for anything that is not utf8 of course, like if someone tries to use documents in some old 8-bit formats or utf16 or something else. But those things were broken anyway. Did not bother with that try-catch since things will go horribly wrong anyway when something like that fails.

**Comment by Beerholder99** [comment]
Not sure if this is completely fixed. With a csv (double-checked to be UTF-8 using Notepad++) going like:
```
RectBase,Puntos,Quality,Combat,Nombre,image,RulesA,RulesB
2,13,3+,4,Potolo el Conquistador,g4260.png,F,più
```  
(extended character is last in second line )
I get 
```
Traceback (most recent call last):
  File "countersheet.py", line 2129, in <module>
    effect.affect()
  File "inkex.py", line 283, in affect
    self.effect()
  File "countersheet.py", line 1440, in effect
    self.options.rotatefronts)
  File "countersheet.py", line 813, in generatecounter
    absref.replace("%%%s%%" % glob, image))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
```
As the error mentions different line numbers than the one from _theclue_ I wonder if the problem could still happen in some other part of the code. _lifelike_ , could you please check? Thanks a million for the extension and your restless support

**Comment by lifelike** [comment]
Yes, looks like an issue with changing file paths to include non-ascii characters (either in the existing absolute path or in the inserted string). Probably requires a fix similar to what was done for the other replaced text.

**Comment by Beerholder99** [comment]
Would you need anything else from me? I can provide the svg and csv if they would help you testing the fix. I feel a bit confused with the explanation as the only "suspicious" character I see in the paths to both svg and csv is a hash (#) and the extension works a charm if the extended character is removed from the csv. Thanks again.

**Comment by lifelike** [comment]
Well, # sounds like a character that is going to cause trouble, as it has a special meaning in URIs. It should not cause ascii decode issues though. If you could open an issue and attach (or mail me) a small example showing this crash it is probably easy to fix.

Have you tried the 1.0 branch btw? I am not likely to make any more releases for Inkscape pre-1.0 (but I could of course push a fix for this particular issue).

**Pull request merged**
