### PR TITLE
Fixes for Inkscape 1.0/MacOSX

### PR DESCRIPTION
**Pull request by jamis**
Hello!

I recently wanted to give your Inkscape extension a try, but was frustrated to find it wouldn't run for me. I do not know for sure if it was purely because I'm using Inkscape 1.0, or because I'm on MacOSX, or both, but either way, I dug in. My Python is extremely rusty, so there may be better ways to do what I've done here, but I figured I'd submit the PR and let you decide if it is worth including or not.

Thanks for a great tool!

### CODE REVIEW

**Comment by lifelike** [comment]
Thanks!

I have some vague memory of changing the popen-code in the past to make it run in Windows. Hopefully this version will work on all systems. Still do not have 1.0 installed anywhere to test this branch myself.

**Comment by lifelike** [comment]
Had to make some minor adjustments to make this work with Inkscape 1.0.1 and Python 2.6.9 on Lubuntu. Hopefully I did not break OSX-support.

But images do not work. Text is replaced OK it seems, and registration marks are added etc, so a lot of stuff works, but not images. Also PDF export is broken (and PNG export not yet tested). Did you have any issues like that in OSX @jamis?

**Comment by jamis** [comment]
Ultimately, I wound up installing Linux in a virtual machine and running a pre-1.0 version of Inkscape, so I could use the stable version.  I'll try and make some time soon to try the OSX version again and see how it looks with this latest commit.

**Comment by lifelike** [comment]
It looks like PDF and PNG exports are stuck in waiting for subprocess, possibly related to the python3-fix you added. If you have time to look into that, that could be very helpful. Otherwise I can have a look tomorrow and I suspect it is just some silly little thing in how the popen-call is made or something (deadlocks when processes are waiting for other processes with i/o pipes open are not unheard of, of course).

Anyway many thanks again for this pr. 1.0 support would be much further away without it.

**Pull request merged**
